### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by maybuksho** [canmet-energy/btap_ml#7] opened 2021-10-26 14:54 UTC
- Create documentation for the functions in the src folder
- update github readme with setup instructions

**Comment by goatsweater** [comment] 2021-11-04 13:34
Producing HTML output from Sphinx from `make html` is good enough of a deliverable for now. PDF generation is a nice to have.

**Comment by srgilani** [comment] 2021-11-19 13:41
Here are some comments/questions on the documentation:
* Weather data processing
•	This is a preprocessing step, correct?
* Preprocessing
•	“simulation I/O output file”: these are input files (annual BTAP-based simulation results) for developing ML models, correct?
•	“the simulation I/O output file used in building and testing the model”: this is the file used as the “in_build_params” file?
•	“the simulation I/O output file used in validating the model”: this is the file used as the “in_build_params_val” file
•	“the weather data for your location of interest”: the weather data should be first preprocessed using the “Weather data processing” step, correct?
* Feature selection
•	Some explanation on why elasticnet has been used (among other methods) would be good
* Model building
•	Some explanation on what “hyperparameter search” is and when it should be used would be good 
•	For “With hyperparameter search”, the “--param_search” should be set as no or yes? 
•	Same question about “Without hyperparameter search”?
•	In the command line under “Model building”, the “feature_selection.py” is run. Should we follow the “Feature selection” step before this as well?

**Comment by maybuksho** [comment] 2021-11-19 18:50
@srgilani , please find my response in bold. Let me know if you have further questions. 
Weather data processing
• This is a preprocessing step, correct? **Do you have any reasons why you think its incorrect, please share.** 
Preprocessing
• “simulation I/O output file”: these are input files (annual BTAP-based simulation results) for developing ML models, correct? **Yes, we also use the epw and the hourly energy consumption file**
• “the simulation I/O output file used in building and testing the model”: this is the file used as the “in_build_params” file? **Yes, that's correct**
• “the simulation I/O output file used in validating the model”: this is the file used as the “in_build_params_val” file? **Yes, however this is optional, if a validation file is not provided, the file provided in in_build_params will be splitted to have the validation set**
• “the weather data for your location of interest”: the weather data should be first preprocessed using the “Weather data processing” step, correct? **Yes, we are focusing on Montreal weather for this project.** 
Feature selection
• Some explanation on why elasticnet has been used (among other methods) would be good. **We have the other feature selection method implemented and can be choosen if desired, however the default feature selection method is "Lasso". I observed that in our case "Lasso" and elasticnet selects almost the same features but either of the approaches would apply
Model building**
• Some explanation on what “hyperparameter search” is and when it should be used would be good. **Hyperparameter search is used to search for the optimal parameters to the model and should be used when you are training the model with dataset containing different conditions. For instance, when we had incorporate data from natural gas, I needed to do an hyperparameter search again. Basically when you are changing parameters in the simulation I/O file, i will do an hyperparameter search before i train the model.** 
• For “With hyperparameter search”, the “--param_search” should be set as no or yes? T**his should be set as yes or no if you desire to run an hyperparameter search when necessary as explained above, otherwise you should choose no. The hyperparameter search runs for about 1-2 hours , however, running the model without hyperparameter search would take about 20minutes. For you to test the model now, i will choose no.** 
• Same question about “Without hyperparameter search”? **For you to test the model now, i will choose no.**
• In the command line under “Model building”, the “feature_selection.py” is run. Should we follow the “Feature selection” step before this as well? **Yes, feature_selection should occur before you build and train the model**

**Comment by goatsweater** [comment] 2021-11-22 13:05
We haven't documented the pipeline yet to show the order operations. I think doing that will make it easier to understand the order of the steps. I have created #27 to ensure that we include it in the documentation.

**Comment by goatsweater** [comment] 2021-11-25 14:24
It would be useful to provide some explanation on when it is best to re-run the hyperparameter search and update the values passed in to `predict.create_model`. Include a brief explanation on how to know what parameter values to pick.

**Comment by goatsweater** [comment] 2021-12-02 20:51
@srgilani & @ckirney The documentation discussed at the meeting today as been merged.

**Comment by ckirney** [comment] 2021-12-07 19:28
I ran into a couple of issues when doing the installation as per the instructions here:

https://canmet-energy.github.io/btap_ml/installation.html#dependency-install

Issue 1:
When doing the pip install I get the following error near the end of the installation:

'ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kubeflow-kale 0.6.1 requires autopep8<1.5,>=1.4, but you have autopep8 1.5.7 which is incompatible.'

I'm not sure if I'm supposed to do anything about it, if someone needs to update the requirements.txt file, or if something else needs to happen.

Issue 2:
As per the 'Pre-commit hooks' section, I type in 'pre-commit install' in main btap_ml repository directory.  When I do, I get the following error:

'bash: pre-commit: command not found'

**Comment by ckirney** [comment] 2021-12-07 19:55
In the 'Quickstart' and 'Train the model' sections one of the first commands to run is:

python prepare_weather.py input_data/sample-config.yml

The documentation should note that the 'prepare_weather.py' file is in the 'src' directory of the btap_ml repo.

**Comment by ckirney** [comment] 2021-12-07 20:10
In the 'Preparation of weather data' section maybe clarify that the user should replace the 'sample-config.yml' file in the command line text with the appropriate btap cli input yaml file.  Also, point out that the file must exist in the MinIO input_data folder.

**Comment by ckirney** [comment] 2021-12-07 20:17
The 'Note' under the 'Clean and split the data' heading in the following page is confusing:

https://canmet-energy.github.io/btap_ml/usage/retrain.html#id5

The last sentence in the 'Note' says "Check Usage for full detail description of each parameter".  I don't know where to look for the information in 'Usage'.

**Comment by srgilani** [comment] 2021-12-08 12:57
* General question
o	How can we use an existing model that has already developed to predict output based on the inputs we give the model? I think the command under the “Re-run Model” section rebuild the model, correct?
* Section “Quickstart”
o	“Preprocessing”: Is it fine that “--in_build_params_gas” and “--in_hour_gas” come after “--output_path”? (in other words, does the order matter)
o	“Preprocessing”: can we have multiple input files? or we should merge them first (e.g. if gas and electricity files are two files)?
* Section “Train the model”
o	 “Similarly, the weather information is aggregated from hourly to daily, so that it can be merged with the hourly energy file.”: “hourly energy file” shouldn’t be “daily energy file”?
* Section “Preprocessing”
o	“in_build_params”: this shouldn’t be annual energy use file?
o	“in_build_params_gas”: same comment

**Comment by goatsweater** [comment] 2021-12-08 13:48
@srgilani the order of the parameters does not matter. Internally the arguments parser sorts things out and the parameters are used in the order they are needed, regardless of how they were provided.

@ckirney the reason you are seeing `bash: pre-commit: command not found` is because pre-commit is installed as part of the development requirements (`requirements-dev.txt`).  We'll need to be more clear that you can skip the pre-commit section when just trying to run things.

**Comment by goatsweater** [comment] 2021-12-09 14:30
Need to update docs on training the model to be clearer about how weather and energy data are summed/merged.

**Comment by goatsweater** [comment] 2021-12-09 14:37
Typo on help text for processing commands. Line in question is https://github.com/canmet-energy/btap_ml/blob/7e286a2a9ab95df00136ba05c00f17f318f45a5a/src/preprocessing.py#L389

**Comment by ckirney** [comment] 2021-12-10 14:00
The new note in the Pre-commit hooks section of the Installation section is helpful.  Although the documentation implies this, I think it would be good to explicitly state that you have to have installed the requirements-dev.txt dependencies for the pre-commit install to work.

**Comment by ckirney** [comment] 2021-12-10 14:05
As I had mentioned earlier, when running the prpare_weather.py file a blank file appears in the weather directory in MinIO along with the parquet file.  In addition to that, if you delete the blank file, it deletes the parquet file as well.

**Comment by ckirney** [comment] 2021-12-10 14:33
I ran the following command (with the output intentionally modified):

python3 preprocessing.py --in_build_params input_data/output_elec_2021-11-05.xlsx --in_hour input_data/total_hourly_res_elec_2021-11-05.csv --in_weather weather/CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.epw.parquet --output_path output_data/preprocessing_out_ck --in_build_params_gas input_data/output_gas_2021-11-05.xlsx --in_hour_gas input_data/total_hourly_res_gas_2021-11-05.csv

It mostly seemed to work and a preprocessing_out_ck file was placed in the MinIO output folder.  However, at the end I got some errors under a '--Logging error--' title.  Is this normal?  The errors are:

--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "preprocessing.py", line 406, in <module>
    process_data(args)
  File "preprocessing.py", line 381, in process_data
    logger.info("write to mino  ", write_to_minio)
Message: 'write to mino  '
Arguments: ('',)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axis.py", line 1489, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/category.py", line 49, in convert
    raise ValueError(
ValueError: Missing category information for StrCategoryConverter; this might be caused by unintendedly mixing categorical and numeric data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocessing.py", line 406, in <module>
    process_data(args)
  File "preprocessing.py", line 384, in process_data
    pl.target_plot(y_train,y_test)
  File "/home/jovyan/btap_ml/src/plot.py", line 58, in target_plot
    plt.hist(y_test, label='test')
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2822, in hist
    return gca().hist(
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/__init__.py", line 1352, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 6659, in hist
    x = [*self._process_unit_info([("x", x[0])], kwargs),
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/artist.py", line 203, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axis.py", line 1491, in convert_units
    raise munits.ConversionError('Failed to convert value(s) to axis '
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: array(['008f3312-a979-44bb-b120-352c957a12fb',
       '008f3312-a979-44bb-b120-352c957a12fb',
       '008f3312-a979-44bb-b120-352c957a12fb', ...,
       'fff8d63d-fbd7-440d-aa4a-9cec8b071295',
       'fff8d63d-fbd7-440d-aa4a-9cec8b071295',
       'fff8d63d-fbd7-440d-aa4a-9cec8b071295'], dtype=object)

**Comment by ckirney** [comment] 2021-12-10 14:40
@maybuksho, I believe I am getting the same error I was before at the feature_selection.py step.  I ran the following command (using the output file with the altered name as described in the above note):

python3 feature_selection.py --in_obj_name output_data/preprocessing_out_ck --output_path output_data/feature_out_ck --estimator_type lasso

I got the following error:

jovyan@btap-chris-0:~/btap_ml/src$ python3 feature_selection.py --in_obj_name output_data/preprocessing_out_ck --output_path output_data/feature_out_ck --estimator_type lassoINFO:config:read minio data at output_data/preprocessing_out_ckINFO:config:Establishing connection to S3 server: http://minio.minio-legacy-system:80
DEBUG:s3fs.core:Open S3 connection.  Anonymous: False
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "feature_selection.py", line 106, in <module>
    select_features(args)
  File "feature_selection.py", line 37, in select_features
    data = acm.access_minio(operation='read',
  File "/home/jovyan/btap_ml/src/config.py", line 107, in access_minio
    logger.info("%s s3 connection %s", s3)
Message: '%s s3 connection %s'
Arguments: (<s3fs.core.S3FileSystem object at 0x7f4a90e0ffa0>,)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): minio.minio-legacy-system:80
DEBUG:urllib3.connectionpool:http://minio.minio-legacy-system:80 "HEAD /nrcan-btap/output_data/preprocessing_out_ck HTTP/1.1" 200 0
INFO:__main__:read from mino <S3File nrcan-btap/output_data/preprocessing_out_ck>
DEBUG:s3fs.core:Fetch: nrcan-btap/output_data/preprocessing_out_ck, 0-1232069681
DEBUG:urllib3.connectionpool:http://minio.minio-legacy-system:80 "GET /nrcan-btap/output_data/preprocessing_out_ck HTTP/1.1" 206 1226826801
   :analysis_id_8f5b5a0d-2823-47f5-baa3-d142c4d878f7  :analysis_id_c24e47f0-5f7e-4318-8775-26573d0d632f  :primary_heating_fuel_Electricity  ...   winddir   windspd  snowdepth
0                                                0.0                                                1.0                                0.0  ...  0.706649  0.516577        1.0
1                                                0.0                                                1.0                                0.0  ...  0.713168  0.434464        1.0
2                                                0.0                                                1.0                                0.0  ...  0.249022  0.500771        1.0
3                                                0.0                                                1.0                                0.0  ...  0.726206  0.633770        1.0
4                                                0.0                                                1.0                                0.0  ...  0.659713  0.270239        1.0
5                                                0.0                                                1.0                                0.0  ...  0.530639  0.454510        1.0
6                                                0.0                                                1.0                                0.0  ...  0.675359  0.446800        1.0
7                                                0.0                                                1.0                                0.0  ...  0.455020  0.232460        1.0
8                                                0.0                                                1.0                                0.0  ...  0.418514  0.427140        1.0
9                                                0.0                                                1.0                                0.0  ...  0.541069  0.244796        1.0

[10 rows x 57 columns]
INFO:numexpr.utils:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "feature_selection.py", line 106, in <module>
    select_features(args)
  File "feature_selection.py", line 77, in select_features
    fit = reg.fit(X_train,y_train)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py", line 1216, in fit
    X, y = self._validate_data(X, y,
  File "/opt/conda/lib/python3.8/site-packages/sklearn/base.py", line 430, in _validate_data
    X = check_array(X, **check_X_params)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 720, in check_array
    _assert_all_finite(array,
  File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 103, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by ckirney** [comment] 2021-12-10 15:19
I ran the following command (with the output intentionally modified):

python3 preprocessing.py --in_build_params input_data/output_elec_2021-11-05.xlsx --in_hour input_data/total_hourly_res_elec_2021-11-05.csv --in_weather weather/CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.epw.parquet --output_path output_data/preprocessing_out_ck --in_build_params_gas input_data/output_gas_2021-11-05.xlsx --in_hour_gas input_data/total_hourly_res_gas_2021-11-05.csv

It mostly seemed to work and a preprocessing_out_ck file was placed in the MinIO output folder. However, at the end I got some errors under a '--Logging error--' title. Is this normal? The errors are:

--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "preprocessing.py", line 406, in <module>
    process_data(args)
  File "preprocessing.py", line 381, in process_data
    logger.info("write to mino  ", write_to_minio)
Message: 'write to mino  '
Arguments: ('',)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axis.py", line 1489, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/category.py", line 49, in convert
    raise ValueError(
ValueError: Missing category information for StrCategoryConverter; this might be caused by unintendedly mixing categorical and numeric data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocessing.py", line 406, in <module>
    process_data(args)
  File "preprocessing.py", line 384, in process_data
    pl.target_plot(y_train,y_test)
  File "/home/jovyan/btap_ml/src/plot.py", line 58, in target_plot
    plt.hist(y_test, label='test')
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2822, in hist
    return gca().hist(
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/__init__.py", line 1352, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 6659, in hist
    x = [*self._process_unit_info([("x", x[0])], kwargs),
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/artist.py", line 203, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axis.py", line 1491, in convert_units
    raise munits.ConversionError('Failed to convert value(s) to axis '
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: array(['008f3312-a979-44bb-b120-352c957a12fb',
       '008f3312-a979-44bb-b120-352c957a12fb',
       '008f3312-a979-44bb-b120-352c957a12fb', ...,
       'fff8d63d-fbd7-440d-aa4a-9cec8b071295',
       'fff8d63d-fbd7-440d-aa4a-9cec8b071295',
       'fff8d63d-fbd7-440d-aa4a-9cec8b071295'], dtype=object)

**Comment by ckirney** [comment] 2021-12-10 15:20
@maybuksho, I believe I am getting the same error I was before at the feature_selection.py step. I ran the following command (using the output file with the altered name as described in the above note):

python3 feature_selection.py --in_obj_name output_data/preprocessing_out_ck --output_path output_data/feature_out_ck --estimator_type lasso

I got the following error:

jovyan@btap-chris-0:~/btap_ml/src$ python3 feature_selection.py --in_obj_name output_data/preprocessing_out_ck --output_path output_data/feature_out_ck --estimator_type lasso
INFO:config:read minio data at output_data/preprocessing_out_ck
INFO:config:Establishing connection to S3 server: http://minio.minio-legacy-system:80
DEBUG:s3fs.core:Open S3 connection.  Anonymous: False
--- Logging error ---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Call stack:
  File "feature_selection.py", line 106, in <module>
    select_features(args)
  File "feature_selection.py", line 37, in select_features
    data = acm.access_minio(operation='read',
  File "/home/jovyan/btap_ml/src/config.py", line 107, in access_minio
    logger.info("%s s3 connection %s", s3)
Message: '%s s3 connection %s'
Arguments: (<s3fs.core.S3FileSystem object at 0x7f91670dbfa0>,)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): minio.minio-legacy-system:80
DEBUG:urllib3.connectionpool:http://minio.minio-legacy-system:80 "HEAD /nrcan-btap/output_data/preprocessing_out_ck HTTP/1.1" 200 0
INFO:__main__:read from mino <S3File nrcan-btap/output_data/preprocessing_out_ck>
DEBUG:s3fs.core:Fetch: nrcan-btap/output_data/preprocessing_out_ck, 0-1232069681
DEBUG:urllib3.connectionpool:http://minio.minio-legacy-system:80 "GET /nrcan-btap/output_data/preprocessing_out_ck HTTP/1.1" 206 1226826801
   :analysis_id_8f5b5a0d-2823-47f5-baa3-d142c4d878f7  :analysis_id_c24e47f0-5f7e-4318-8775-26573d0d632f  :primary_heating_fuel_Electricity  ...   winddir   windspd  snowdepth
0                                                0.0                                                1.0                                0.0  ...  0.706649  0.516577        1.0
1                                                0.0                                                1.0                                0.0  ...  0.713168  0.434464        1.0
2                                                0.0                                                1.0                                0.0  ...  0.249022  0.500771        1.0
3                                                0.0                                                1.0                                0.0  ...  0.726206  0.633770        1.0
4                                                0.0                                                1.0                                0.0  ...  0.659713  0.270239        1.0
5                                                0.0                                                1.0                                0.0  ...  0.530639  0.454510        1.0
6                                                0.0                                                1.0                                0.0  ...  0.675359  0.446800        1.0
7                                                0.0                                                1.0                                0.0  ...  0.455020  0.232460        1.0
8                                                0.0                                                1.0                                0.0  ...  0.418514  0.427140        1.0
9                                                0.0                                                1.0                                0.0  ...  0.541069  0.244796        1.0

[10 rows x 57 columns]
INFO:numexpr.utils:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "feature_selection.py", line 106, in <module>
    select_features(args)
  File "feature_selection.py", line 77, in select_features
    fit = reg.fit(X_train,y_train)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py", line 1216, in fit
    X, y = self._validate_data(X, y,
  File "/opt/conda/lib/python3.8/site-packages/sklearn/base.py", line 430, in _validate_data
    X = check_array(X, **check_X_params)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 720, in check_array
    _assert_all_finite(array,
  File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 103, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by goatsweater** [comment] 2021-12-10 15:46
The logging errors are a syntax bug, but won't impact anything (although you don't get to see whatever message was trying to be logged). These always start with "logging error". Other stuff is more impactful and needs to be fixed for you to make progress.

**Comment by srgilani** [comment] 2021-12-10 18:27
* It might be good to mention which git repository to clone in this step: https://github.com/canmet-energy/btap_ml/blob/main/docs/aaw_setup.rst#project-source-code
* Might also be good to explain how to create a terminal in JupyterLab after cloning the git repository.
* It would be good to mention where to run the commands for installing dependencies: https://github.com/canmet-energy/btap_ml/blob/main/docs/installation.rst#dependencies

**Comment by goatsweater** [comment] 2021-12-10 20:58
> As I had mentioned earlier, when running the prpare_weather.py file a blank file appears in the weather directory in MinIO along with the parquet file. In addition to that, if you delete the blank file, it deletes the parquet file as well.

@ckirney I wasn't able to replicate creating the blank file, but when I tested it I did delete the blank file and definitely didn't experience it deleting the main file. I created #45 to work on this.

**Comment by goatsweater** [comment] 2021-12-13 15:12
> @goatsweater, that is odd. I tried it a few more times and found that not only does deleting the blank file delete the accompanying parquet file, it deletes everything in the folder. I believe @srgilani tried it too and had the same issue.

Ok. good to know you're able to replicate it. We'll have to implement some finer grained tracing to figure it out. The blank file doesn't seem to be impacting anything other than being annoying, so not an immediate blocker.

**Comment by goatsweater** [comment] 2021-12-13 17:58
We've identified a cause for feature selection to constantly fail. The problem is being tracked in #53. Likely won't have the fix in place before tomorrow to continue testing.

**Comment by goatsweater** [comment] 2021-12-14 13:29
@ckirney & @srgilani I've merged the changes required to make feature selection run through successfully. I've also adjusted the quickstart docs to ensure they reflect the correct commands.

You'll still notice a crash at the end of `preprocessing.py`. This doesn't affect the outputs at all, it's just trying to draw a plot which fails at the command line interface. I've recorded the failure in #56. There's no reason to wait for that to be fixed before continuing with your testing.

**Comment by ckirney** [comment] 2021-12-14 14:09
Thanks @goatsweater, I'll start testing.  Did you fix the issue of an empty file being created when the weather .parquet file is created when running prepare_weather.py?  I only ask because it didn't happen for me this time.

**Comment by goatsweater** [comment] 2021-12-14 14:13
I did have to make a change to prepare_weather.py, but not that I would expect to address #45. Glad it's working properly though.

**Comment by ckirney** [comment] 2021-12-14 18:37
I have successfully completed the 'Build the surrogate model and predict energy use' step of the modeling process and am looking at the results.  It would be nice if the 'predict_out' output file had a file extension so I had an idea of what to expect and how to view it (it seems to be a json file so adding a .json would be nice if that is correct).  If this is something that should be added when running the predict.py file then it should be noted in the documentation.  It would also be nice if the 'predict_out' output file was described in the documentation (what the keys mean, units for the values, what each set of values in the output_df array are, etc.).  I recall that they were described to me but do not remember what they are.  Generally, I have the same comment for all of the output files (feature_out, and preprocessing_out).

**Comment by maybuksho** [comment] 2021-12-15 20:06
@ckirney definitely , you can simply change the name output file produced e.g specify predict.json , that would create the json extension.  Useful feedback on documenting the keys used in the file. i will incorporate this in the documentation

**Comment by ckirney** [comment] 2021-12-15 20:43
@maybuksho, yes I can add .json to the name of the file.  I just wanted to make sure that that was the format I was supposed to use.  Also, are the feature_out and preprocessing_out files also .json?

**Comment by maybuksho** [comment] 2021-12-16 19:20
> * It might be good to mention which git repository to clone in this step: https://github.com/canmet-energy/btap_ml/blob/main/docs/aaw_setup.rst#project-source-code
> * Might also be good to explain how to create a terminal in JupyterLab after cloning the git repository.
> * It would be good to mention where to run the commands for installing dependencies: https://github.com/canmet-energy/btap_ml/blob/main/docs/installation.rst#dependencies

I updated the documentation to include the git link to the repo for cloning. I specified running the command from the terminal just from one section, to avoid redundancy

**Comment by maybuksho** [comment] 2021-12-16 19:23
> @maybuksho, yes I can add .json to the name of the file. I just wanted to make sure that that was the format I was supposed to use. Also, are the feature_out and preprocessing_out files also .json?

Yes they are all json file. I have updated the documentation to reflect definition for the keys.

**Closed** 2021-12-17 18:01 UTC
Labels: documentation
